/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenFileRouteImport } from './routes/citizen.file'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerLoginRouteImport } from './routes/officer.login'
import { Route as OfficerComplaintsIdRouteImport } from './routes/officer.complaints.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenFileRoute = CitizenFileRouteImport.update({
  id: '/citizen/file',
  path: '/citizen/file',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/officer/login',
  path: '/officer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerComplaintsIdRoute = OfficerComplaintsIdRouteImport.update({
  id: '/officer/complaints/$id',
  path: '/officer/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/login': typeof OfficerLoginRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/login': typeof OfficerLoginRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/citizen/file': typeof CitizenFileRoute
  '/officer/login': typeof OfficerLoginRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/login'
    | '/citizen/'
    | '/officer/'
    | '/officer/complaints/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/login'
    | '/citizen'
    | '/officer'
    | '/officer/complaints/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/track'
    | '/citizen/file'
    | '/officer/login'
    | '/citizen/'
    | '/officer/'
    | '/officer/complaints/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  CitizenFileRoute: typeof CitizenFileRoute
  OfficerLoginRoute: typeof OfficerLoginRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerComplaintsIdRoute: typeof OfficerComplaintsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/file': {
      id: '/citizen/file'
      path: '/citizen/file'
      fullPath: '/citizen/file'
      preLoaderRoute: typeof CitizenFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/login': {
      id: '/officer/login'
      path: '/officer/login'
      fullPath: '/officer/login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/complaints/$id': {
      id: '/officer/complaints/$id'
      path: '/officer/complaints/$id'
      fullPath: '/officer/complaints/$id'
      preLoaderRoute: typeof OfficerComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  CitizenFileRoute: CitizenFileRoute,
  OfficerLoginRoute: OfficerLoginRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerComplaintsIdRoute: OfficerComplaintsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
